# EXPECT: Low PORT-PUBLISHED-ALL-IFACES
services:
  app:
    image: nginx@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    user: "10001"
    read_only: true
    ports:
      - "8080:80"
