# EXPECT: High HOST-NETWORK-MODE
services:
  app:
    image: nginx@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    user: "10001"
    read_only: true
    network_mode: host
