# EXPECT: Medium SECRET-IN-ENVIRONMENT
services:
  app:
    image: nginx@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    user: "10001"
    read_only: true
    environment:
      API_KEY: "sk-abc123def456ghi789"
