# EXPECT: High WEAK-DEFAULT-CREDENTIAL
services:
  db:
    image: nginx@sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa
    user: "10001"
    read_only: true
    environment:
      POSTGRES_PASSWORD: postgres
